<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Serilog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kernel\NafasLand.Admin.Shared.Kernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NafasLand.Admin.Shared.Kernel.Tests" />
    <InternalsVisibleTo Include="NafasLand.Admin.Modules.Sample.Tests" />
  </ItemGroup>

</Project>
