/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/identity/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserListItemResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateUserResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetUserRolesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/users/{id}/permissions/{permissionKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    permissionKey: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetUserPermissionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/roles/{roleId}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roleId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetRolePermissionsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/users/{id}/toggle-active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ToggleUserActiveResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDetailsResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PermissionResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoleResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/roles/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoleSummaryResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sample/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sample/unprotected-ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    actorUserId?: string;
                    from?: string;
                    to?: string;
                    action?: string;
                    entityType?: string;
                    outcome?: components["schemas"]["AuditOutcome"];
                    cursor?: string;
                    pageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditLogPageDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditLogDetailDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    cursor?: string;
                    pageSize?: number | string;
                };
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserActivityDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/products/{externalProductId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    pageSize?: number | string;
                    variantId?: string[];
                };
                header?: never;
                path: {
                    externalProductId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductAuditHistoryDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/actors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditActorDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/export/{jobId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditExportStatusDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/export/{jobId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExportAuditLogRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditExportAcceptedDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    status?: string;
                    type?: string;
                    mine?: boolean;
                    targetEntityType?: string;
                    targetEntityId?: string;
                    cursor?: string;
                    pageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateApprovalRequestRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateApprovalRequestResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": null | components["schemas"]["ApproveApprovalRequestRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApprovalDecisionResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{id}/rejection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RejectApprovalRequestRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApprovalDecisionResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{id}/cancellation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApprovalDecisionResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApprovalDecisionResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    page: number | string;
                    pageSize: number | string;
                    keywords?: string;
                    sorting?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PortalProductListResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProductRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateProductResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/products/{externalProductId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    externalProductId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PortalProductDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PortalTaxonomyResultOfPortalCategoryNode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PortalTaxonomyResultOfPortalFilterGroup"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProductRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateProductResult"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/products/variants/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    variantId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateVariantPriceAndInventoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateVariantPriceAndInventoryResult"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/returns/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderPreviewDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    pageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReturnRecordPageDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/returns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReturnRecordDetailDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActionCountDto: {
            action: string;
            outcome: string;
            /** Format: int32 */
            count: number | string;
        };
        ApprovalDecisionResult: {
            /** Format: uuid */
            id: string;
            status: string;
            executionError: null | string;
        };
        ApproveApprovalRequestRequest: {
            note: null | string;
        };
        AuditActorDto: {
            /** Format: uuid */
            userId: string;
            username: null | string;
        };
        AuditExportAcceptedDto: {
            /** Format: uuid */
            jobId: string;
        };
        AuditExportStatusDto: {
            /** Format: uuid */
            id: string;
            status: string;
            format: string;
            errorMessage: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt: null | string;
        };
        AuditLogDetailDto: {
            /** Format: uuid */
            id: string;
            correlationId: string;
            /** Format: uuid */
            actorUserId: null | string;
            actorUsername: null | string;
            /** Format: uuid */
            onBehalfOfUserId: null | string;
            onBehalfOfUsername: null | string;
            actorRoleAtTime: string;
            action: string;
            entityType: null | string;
            entityId: null | string;
            parentEntityType: null | string;
            parentEntityId: null | string;
            before: null | components["schemas"]["JsonElement"];
            after: null | components["schemas"]["JsonElement"];
            changedFields: null | components["schemas"]["JsonElement"];
            outcome: string;
            /** Format: int32 */
            upstreamStatus: null | number | string;
            failureReason: null | string;
            ipAddress: null | string;
            userAgent: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        AuditLogPageDto: {
            items: components["schemas"]["AuditLogSummaryDto"][];
            nextCursor: null | string;
        };
        AuditLogSummaryDto: {
            /** Format: uuid */
            id: string;
            correlationId: string;
            /** Format: uuid */
            actorUserId: null | string;
            actorUsername: null | string;
            actorRoleAtTime: string;
            action: string;
            entityType: null | string;
            entityId: null | string;
            outcome: string;
            failureReason: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        AuditOutcome: number;
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        CreateApprovalRequestRequest: {
            requestType: string;
            targetEntityType: string;
            targetEntityId: string;
            reason: string;
            payload: components["schemas"]["JsonElement"];
        };
        CreateApprovalRequestResult: {
            /** Format: uuid */
            id: string;
            requestType: string;
            status: string;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            expiresAt: null | string;
        };
        CreateProductRequest: {
            title: string;
            caption: null | string;
            description: null | string;
            contents: components["schemas"]["PortalNameValue"][];
            commentingEnabled: boolean;
            fields: components["schemas"]["PortalNameValue"][];
            slug: null | string;
            metaTitle: null | string;
            metaDescription: null | string;
            metaKeywords: null | string;
            metaRobots: null | string;
            redirect: null | string;
            categoryIds: (number | string)[];
            filterIds: (number | string)[];
            attributes: components["schemas"]["PortalAttribute"][];
            variants: components["schemas"]["CreateProductVariantInput"][];
        };
        CreateProductResult: {
            id: string;
            version: null | string;
            title: null | string;
        };
        CreateProductVariantInput: {
            title: string;
            /** Format: double */
            price: null | number | string;
            /** Format: double */
            comparePrice: null | number | string;
            /** Format: double */
            tax: null | number | string;
            /** Format: double */
            shipping: null | number | string;
            /** Format: double */
            weight: null | number | string;
            /** Format: double */
            length: null | number | string;
            /** Format: double */
            width: null | number | string;
            /** Format: double */
            height: null | number | string;
            /** Format: int32 */
            stock: null | number | string;
            /** Format: int32 */
            minimum: null | number | string;
            /** Format: int32 */
            maximum: null | number | string;
            sku: null | string;
        };
        CreateUserRequest: {
            username: string;
            initialPassword: string;
        };
        CreateUserResult: {
            /** Format: uuid */
            id: string;
            username: string;
        };
        DirectPermissionResponse: {
            key: string;
            effect: string;
        };
        ExportAuditLogRequest: {
            /** Format: uuid */
            actorUserId: null | string;
            /** Format: date-time */
            from: null | string;
            /** Format: date-time */
            to: null | string;
            action: null | string;
            entityType: null | string;
            outcome: null | string;
            format: string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        JsonElement: unknown;
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResult: {
            /** Format: uuid */
            userId: string;
            username: string;
            mustChangePassword: boolean;
            antiforgeryToken: string;
        };
        MeResponse: {
            /** Format: uuid */
            id: string;
            username: string;
            mustChangePassword: boolean;
            isActive: boolean;
            roles: string[];
            permissions: string[];
        };
        OrderItemDto: {
            /** Format: int64 */
            productId: null | number | string;
            /** Format: int64 */
            variantId: null | number | string;
            title: null | string;
            /** Format: double */
            price: null | number | string;
            /** Format: int32 */
            quantity: number | string;
        };
        OrderPreviewDto: {
            /** Format: int64 */
            orderId: number | string;
            statuses: string[];
            customerName: null | string;
            /** Format: double */
            subtotal: null | number | string;
            /** Format: double */
            shipping: null | number | string;
            /** Format: double */
            discount: null | number | string;
            /** Format: double */
            tax: null | number | string;
            /** Format: double */
            total: null | number | string;
            /** Format: date-time */
            createdAtUtc: null | string;
            items: components["schemas"]["OrderItemDto"][];
            ineligibilityReason: null | string;
        };
        OutcomeCountDto: {
            outcome: string;
            /** Format: int32 */
            count: number | string;
        };
        PermissionResponse: {
            key: string;
            displayName: string;
            moduleName: string;
            isSuperAdminOnly: boolean;
        };
        PingRequest: {
            message: string;
        };
        PortalAttribute: {
            name: string;
            value: string[];
        };
        PortalCategoryNode: {
            id: string;
            title: null | string;
            type: null | string;
            children: components["schemas"]["PortalCategoryNode"][];
        };
        PortalFilterGroup: {
            id: string;
            title: null | string;
            /** Format: int32 */
            weight: null | number | string;
            values: components["schemas"]["PortalTaxonomyValue"][];
        };
        PortalNameValue: {
            name: string;
            value: null | string;
        };
        PortalProductDetail: {
            id: string;
            title: null | string;
            caption: null | string;
            slug: null | string;
            url: null | string;
            description: null | string;
            contents: components["schemas"]["PortalNameValue"][];
            commentingEnabled: boolean;
            fields: components["schemas"]["PortalNameValue"][];
            attributes: components["schemas"]["PortalAttribute"][];
            /** Format: double */
            price: null | number | string;
            /** Format: date-time */
            publishedAtUtc: null | string;
            /** Format: date-time */
            createdAtUtc: null | string;
            statuses: string[];
            categories: components["schemas"]["PortalTaxonomyValue"][];
            filters: components["schemas"]["PortalTaxonomyValue"][];
            image: null | string;
            images: components["schemas"]["PortalProductImage"][];
            variants: components["schemas"]["PortalProductVariant"][];
            relates: (number | string)[];
            metaTitle: null | string;
            metaDescription: null | string;
            metaKeywords: null | string;
            metaRobots: null | string;
            redirect: null | string;
            canonicalUrl: null | string;
            version: null | string;
            /** @default false */
            isStale: boolean;
            /** Format: date-time */
            asOfUtc?: null | string;
            isPending?: boolean;
            isAvailable?: boolean;
        };
        PortalProductImage: {
            path: string;
            title: null | string;
        };
        PortalProductListResult: {
            items: components["schemas"]["PortalProductSummary"][];
            /** Format: int32 */
            total: number | string;
            /** Format: int32 */
            count: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** @default false */
            isStale: boolean;
            /** Format: date-time */
            asOfUtc?: null | string;
        };
        PortalProductSummary: {
            id: string;
            title: null | string;
            slug: null | string;
            url: null | string;
            /** Format: double */
            price: null | number | string;
            /** Format: date-time */
            createdAtUtc: null | string;
            statuses: string[];
            isPending?: boolean;
            isAvailable?: boolean;
        };
        PortalProductVariant: {
            id: null | string;
            productId: null | string;
            title: null | string;
            /** Format: double */
            price: null | number | string;
            /** Format: double */
            comparePrice: null | number | string;
            /** Format: double */
            tax: null | number | string;
            /** Format: double */
            shipping: null | number | string;
            /** Format: double */
            weight: null | number | string;
            /** Format: double */
            length: null | number | string;
            /** Format: double */
            width: null | number | string;
            /** Format: double */
            height: null | number | string;
            /** Format: int32 */
            stock: null | number | string;
            /** Format: int32 */
            minimum: null | number | string;
            /** Format: int32 */
            maximum: null | number | string;
            sku: null | string;
            image: null | string;
            type: null | string;
            status: string[];
            files: string[];
        };
        PortalTaxonomyResultOfPortalCategoryNode: {
            items: components["schemas"]["PortalCategoryNode"][];
            /** @default false */
            isStale: boolean;
            /** Format: date-time */
            asOfUtc?: null | string;
        };
        PortalTaxonomyResultOfPortalFilterGroup: {
            items: components["schemas"]["PortalFilterGroup"][];
            /** @default false */
            isStale: boolean;
            /** Format: date-time */
            asOfUtc?: null | string;
        };
        PortalTaxonomyValue: {
            id: string;
            title: null | string;
            url: null | string;
            /** Format: int32 */
            weight: null | number | string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        ProductAuditHistoryDto: {
            externalProductId: string;
            lastKnownTitle: null | string;
            /** Format: date-time */
            lastSyncedAt: null | string;
            items: components["schemas"]["AuditLogSummaryDto"][];
            nextCursor: null | string;
        };
        RejectApprovalRequestRequest: {
            note: string;
        };
        ResetPasswordRequest: {
            newPassword: string;
        };
        ReturnRecordDetailDto: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            orderId: number | string;
            customerName: null | string;
            orderStatuses: string[];
            /** Format: date-time */
            orderCreatedAtUtc: null | string;
            /** Format: double */
            subtotal: null | number | string;
            /** Format: double */
            shipping: null | number | string;
            /** Format: double */
            discount: null | number | string;
            /** Format: double */
            tax: null | number | string;
            /** Format: double */
            total: null | number | string;
            items: components["schemas"]["OrderItemDto"][];
            reason: string;
            /** Format: date */
            returnDate: string;
            /** Format: uuid */
            registeredByUserId: string;
            registeredByUsername: null | string;
            /** Format: date-time */
            registeredAt: string;
            /** Format: uuid */
            approvedByUserId: string;
            approvedByUsername: null | string;
            /** Format: date-time */
            approvedAt: string;
        };
        ReturnRecordPageDto: {
            items: components["schemas"]["ReturnRecordSummaryDto"][];
            nextCursor: null | string;
        };
        ReturnRecordSummaryDto: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            orderId: number | string;
            customerName: null | string;
            /** Format: double */
            total: null | number | string;
            /** Format: date */
            returnDate: string;
            /** Format: uuid */
            registeredByUserId: string;
            registeredByUsername: null | string;
            /** Format: date-time */
            registeredAt: string;
            /** Format: uuid */
            approvedByUserId: string;
            approvedByUsername: null | string;
            /** Format: date-time */
            approvedAt: string;
        };
        RoleResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            isSystemManaged: boolean;
            permissionKeys: string[];
        };
        RoleSummaryResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            isSystemManaged: boolean;
        };
        SetRolePermissionsRequest: {
            permissionKeys: string[];
        };
        SetUserPermissionRequest: {
            effect: null | string;
        };
        SetUserRolesRequest: {
            roleIds: string[];
        };
        ToggleUserActiveResult: {
            isActive: boolean;
        };
        UpdateProductContentInput: {
            name: string;
            value: null | string;
            isDirty: boolean;
        };
        UpdateProductRequest: {
            lastKnownVersion: string;
            title: string;
            caption: null | string;
            description: null | string;
            descriptionDirty: boolean;
            contents: components["schemas"]["UpdateProductContentInput"][];
            commentingEnabled: boolean;
            fields: components["schemas"]["PortalNameValue"][];
            slug: null | string;
            metaTitle: null | string;
            metaDescription: null | string;
            metaKeywords: null | string;
            metaRobots: null | string;
            redirect: null | string;
            categoryIds: (number | string)[];
            filterIds: (number | string)[];
        };
        UpdateProductResult: {
            id: string;
            version: null | string;
            title: null | string;
        };
        UpdateVariantPriceAndInventoryRequest: {
            /** Format: double */
            newPrice: number | string;
            /** Format: int32 */
            newStock: number | string;
            /** Format: double */
            lastKnownPrice: null | number | string;
            /** Format: int32 */
            lastKnownStock: null | number | string;
        };
        UpdateVariantPriceAndInventoryResult: {
            variantId: string;
            /** Format: double */
            price: number | string;
            /** Format: int32 */
            stock: number | string;
        };
        UserActivityDto: {
            /** Format: uuid */
            userId: string;
            username: null | string;
            countsByOutcome: components["schemas"]["OutcomeCountDto"][];
            countsByAction: components["schemas"]["ActionCountDto"][];
            timeline: components["schemas"]["AuditLogPageDto"];
        };
        UserDetailsResponse: {
            /** Format: uuid */
            id: string;
            username: string;
            isActive: boolean;
            isProtected: boolean;
            mustChangePassword: boolean;
            /** Format: date-time */
            createdAt: string;
            roles: string[];
            directPermissions: components["schemas"]["DirectPermissionResponse"][];
        };
        UserListItemResponse: {
            /** Format: uuid */
            id: string;
            username: string;
            isActive: boolean;
            isProtected: boolean;
            mustChangePassword: boolean;
            roles: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
