<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Shared\Kernel\NafasLand.Admin.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\src\Shared\Infrastructure\NafasLand.Admin.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Sample\NafasLand.Admin.Modules.Sample.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\NafasLand.Admin.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\src\Modules\Auditing\NafasLand.Admin.Modules.Auditing.csproj" />
  </ItemGroup>

</Project>
