<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Kernel\NafasLand.Admin.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\Shared\Infrastructure\NafasLand.Admin.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NafasLand.Admin.Modules.Sample.Tests" />
  </ItemGroup>

</Project>
